#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


FIXTURES="tests/fixtures"
PLAIN="$FIXTURES/plain.xlsx"
MACROS="$FIXTURES/macros.xlsm"
FEATURE="$FIXTURES/feature.xlsx"
DATED="$FIXTURES/dated-row.xlsx"

# A fixture that exists is a baseline, so a wizard that walks you back through
# building one is a wizard inviting you to re-save it. A run that finds the
# three of #4 already saved is therefore a run about the fourth alone.
if [[ -f "$PLAIN" && -f "$MACROS" && -f "$FEATURE" ]]; then
  MODE=fourth
  TOTAL_STAGES=4
  FIRST_SAVED=2026-09-11   # when the three were saved, which is not today
else
  MODE=all
  TOTAL_STAGES=12
  FIRST_SAVED=$(date +%Y-%m-%d)
fi

# ── Verification helpers ──────────────────────────────────────────────────
# Issue #4 can be got subtly wrong in ways that only bite three tickets
# later, so every file is unzipped and checked the moment it is saved.

FAILED=0

# part PATTERN FILE: the text of the matching part(s) of a package.
part() { unzip -p "$2" "$1" 2>/dev/null || true; }

# check "label" HAYSTACK REGEX: pass when the regex matches.
check() {
  if printf '%s' "$2" | grep -qE "$3"; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"
    FAILED=$((FAILED + 1))
  fi
}

# refute "label" HAYSTACK REGEX: pass when the regex does NOT match.
refute() {
  if printf '%s' "$2" | grep -qE "$3"; then
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"
    FAILED=$((FAILED + 1))
  else
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  fi
}

# saved FILE: the file exists and is a zip container.
saved() {
  if [[ ! -f "$1" ]]; then
    printf '  %s✗%s %s was not saved to that path\n' "$RED" "$RESET" "$1"
    FAILED=$((FAILED + 1)); return 1
  fi
  if ! unzip -l "$1" >/dev/null 2>&1; then
    printf '  %s✗%s %s is not a package\n' "$RED" "$RESET" "$1"
    FAILED=$((FAILED + 1)); return 1
  fi
  printf '  %s✓%s %s saved (%s)\n' "$GREEN" "$RESET" "$1" "$(du -h "$1" | cut -f1)"
}

# dated_row FILE ROW: the row declares a custom format, and the style it
# points at is a date format. Excel writes a styles part as one long line of
# regular output, so this reads it with grep rather than pretending to parse
# XML: the alternative is a dependency, for a check on four small files.
dated_row() {
  local file="$1" row="$2" sheet element index xfs numfmt code kind=no
  sheet=$(part "xl/worksheets/sheet*.xml" "$file")
  element=$(printf '%s' "$sheet" | grep -oE "<(x:)?row r=\"$row\"[^>]*>" | head -n1)
  if [[ -z "$element" ]]; then
    printf '  %s✗%s the sheet has no row %s at all\n' "$RED" "$RESET" "$row"
    FAILED=$((FAILED + 1)); return 1
  fi
  check "row $row declares a custom format" "$element" 'customFormat="1"'

  index=$(printf '%s' "$element" | grep -oE ' s="[0-9]+"' | grep -oE '[0-9]+' | head -n1)
  if [[ -z "$index" ]]; then
    printf '  %s✗%s row %s points at no style, so it carries no format\n' "$RED" "$RESET" "$row"
    FAILED=$((FAILED + 1)); return 1
  fi

  # The row's style index counts into cellXfs, and the entry it lands on names
  # the number format. cellStyleXfs holds xf elements too, hence the slice.
  local styles; styles=$(part "xl/styles.xml" "$file" | tr '\n' ' ')
  xfs=$(printf '%s' "$styles" | sed -n 's/.*<\(x:\)\{0,1\}cellXfs[^>]*>\(.*\)<\/\(x:\)\{0,1\}cellXfs>.*/\2/p')
  numfmt=$(printf '%s' "$xfs" | grep -oE '<(x:)?xf [^>]*>' | sed -n "$((index + 1))p" \
    | grep -oE 'numFmtId="[0-9]+"' | grep -oE '[0-9]+' | head -n1)
  case "${numfmt:-}" in
  1[4-7] | 22) kind=yes ;;                     # the built-in date formats
  "" | 0) kind=no ;;
  *)
    code=$(printf '%s' "$styles" \
      | grep -oE "<(x:)?numFmt[^>]*numFmtId=\"$numfmt\"[^>]*>" \
      | grep -oE 'formatCode="[^"]*"' | head -n1)
    case "$code" in
    *y* | *Y* | *d* | *D*) kind=yes ;;         # a custom format naming a date
    esac
    ;;
  esac
  if [[ "$kind" == yes ]]; then
    printf '  %s✓%s the format row %s carries is a DATE format (numFmtId %s)\n' \
      "$GREEN" "$RESET" "$row" "${numfmt:-?}"
  else
    printf '  %s✗%s row %s carries numFmtId %s, which is not a date format\n' \
      "$RED" "$RESET" "$row" "${numfmt:-none}"
    note "  Select the whole row by its header before formatting: formatting"
    note "  the cell alone leaves the row carrying General, which is the case"
    note "  feature.xlsx already covers."
    FAILED=$((FAILED + 1))
  fi
}

# verdict "name": report and let the human retry the stage.
verdict() {
  if (( FAILED == 0 )); then
    printf '\n  %s%s✓ %s meets the ticket%s\n' "$BOLD" "$GREEN" "$1" "$RESET"
  else
    printf '\n'
    warn "$FAILED check(s) failed on $1."
    note "Fix it in Excel and save over the same path, then re-run this wizard."
    note "A file that never left Excel has no byte history to protect yet, so"
    note "re-saving now is free. Once it is committed, it must not be re-saved."
  fi
  FAILED=0
}

if [[ "$MODE" == fourth ]]; then
  banner "xlsplice fixtures — the dated row (issue #28)"
else
  banner "xlsplice fixtures (issues #4 and #28)"
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Ground rules"
if [[ "$MODE" == fourth ]]; then
  say "The three packages of #4 are already saved, so this run is about the"
  say "fourth alone: a package with a row whose custom format is a DATE"
  say "format. Nothing here touches the three that exist."
else
  say "Four packages go into $FIXTURES/, saved by you from Excel."
fi
printf '\n'
step "Keep every file small: a handful of cells, no styling beyond what is asked."
step "No vendor material. Nothing from a customer template, not one cell."
step "Clear the author fields before saving: File > Info > Inspect Workbook >"
step "  Document Properties and Personal Information. A saved name ends up in"
step "  docProps/core.xml and ships with every release."
step "Save each file ONCE and never re-save it. Its bytes are the test baseline."
step "Build each workbook completely BEFORE saving, so one save is enough."
printf '\n'
if ! command -v unzip >/dev/null 2>&1; then
  warn "unzip is not on PATH, so this wizard cannot verify what you save."
  exit 1
fi
mkdir -p "$FIXTURES"
note "created $FIXTURES/"
pause "Ready?"

# ── The three packages of issue #4 ────────────────────────────────────────
# Only built when they are not on disk. The body is left unindented so that
# the diff that wrapped it shows what it wrapped, and nothing else.
if [[ "$MODE" == all ]]; then

# ──────────────────────────────────────────────────────────────────────────
stage "1 of 4 · plain.xlsx"
say "A plain workbook: one visible sheet, a few numbers, a text, a date"
say "formatted as a date, and a boolean."
printf '\n'
step "Excel → File → New Blank Workbook. Leave the one sheet as Sheet1."
step "A1: 1     A2: 2.5     A3: -3"
step "B1: hello"
step "C1: 2026-09-11 — then Format → Cells → Date, so it is a DATE not text."
step "D1: TRUE   (type the word; Excel stores a real boolean)"
printf '\n'
step "File → Save As → Format: Excel Workbook (.xlsx)"
step "Save it at exactly:  $(pwd)/$PLAIN"
step "Then CLOSE the workbook."
printf '\n'
pause "Press Enter once it is saved and closed."
printf '\n'
if saved "$PLAIN"; then
  wb=$(part "xl/workbook.xml" "$PLAIN")
  sheet=$(part "xl/worksheets/sheet*.xml" "$PLAIN")
  styles=$(part "xl/styles.xml" "$PLAIN")
  # BSD grep -c counts matches, GNU grep -c counts lines, and Excel writes
  # workbook.xml as one long line. Count with wc so both agree.
  check "exactly one sheet" \
    "$(printf '%s' "$wb" | grep -oE '<(x:)?sheet ' | wc -l | tr -d ' ')" '^1$'
  refute "that sheet is visible" "$wb" 'state="(hidden|veryHidden)"'
  check "holds a boolean cell" "$sheet" 't="b"'
  check "holds a text cell" "$sheet" 't="(s|inlineStr|str)"'
  check "holds numeric values" "$sheet" '<(x:)?v>'
  check "a date number format is defined" "$styles" 'numFmtId="(1[4-9]|2[0-2]|4[5-7])"|formatCode="[^"]*(yy|dd|mmm)'
fi
verdict "plain.xlsx"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "2 of 4 · macros.xlsm"
say "A macro-enabled workbook with a REAL VBA project, so the pass-through of"
say "xl/vbaProject.bin is exercised. Any trivial macro will do."
printf '\n'
step "Excel → File → New Blank Workbook."
step "A1: 1"
step "Tools → Macro → Visual Basic Editor   (or Developer → Visual Basic)"
step "In the editor: Insert → Module, then paste exactly:"
printf '\n      %sSub Hello()%s\n' "$DIM" "$RESET"
printf '      %s    MsgBox "hi"%s\n' "$DIM" "$RESET"
printf '      %sEnd Sub%s\n\n' "$DIM" "$RESET"
step "Close the editor and go back to Excel."
printf '\n'
step "File → Save As → Format: Excel Macro-Enabled Workbook (.xlsm)"
step "Save it at exactly:  $(pwd)/$MACROS"
step "Then CLOSE the workbook."
printf '\n'
warn "A .xlsm with no module saves no vbaProject.bin. The macro is the point."
printf '\n'
pause "Press Enter once it is saved and closed."
printf '\n'
if saved "$MACROS"; then
  listing=$(unzip -l "$MACROS" 2>/dev/null || true)
  types=$(part "\[Content_Types\].xml" "$MACROS")
  check "carries a real VBA project (xl/vbaProject.bin)" "$listing" 'xl/vbaProject\.bin'
  check "the VBA part is not empty" \
    "$(printf '%s' "$listing" | grep -E 'vbaProject\.bin' | awk '{print $1}')" '^[1-9][0-9]*$'
  check "declared macro-enabled in [Content_Types].xml" "$types" 'sheet\.macroEnabled\.main\+xml'
fi
verdict "macros.xlsm"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "3 of 4 · feature.xlsx — sheets and visibility"
say "The feature workbook is built across the next five stages and saved ONCE"
say "at the end. Do not save until this wizard tells you to."
printf '\n'
step "Excel → File → New Blank Workbook."
step "Rename Sheet1 to:  Inputs"
step "Add two more sheets, named:  Notes  and  Parameters"
step "On Notes, put any text in A5 (a sheet-scoped name will point there)."
printf '\n'
say "Now hide two of them. Do the plain hide first:"
step "Right-click the Notes tab → Hide"
printf '\n'
say "veryHidden cannot be set from the worksheet UI. Use the VBA editor:"
step "Click the Inputs tab first, so the feature workbook is the active one."
step "Tools → Macro → Visual Basic Editor"
step "View → Immediate Window, then type this line and press Enter:"
printf '\n      %sActiveWorkbook.Sheets("Parameters").Visible = 2%s\n\n' "$DIM" "$RESET"
note "2 is xlSheetVeryHidden. The Immediate window runs the line without"
note "storing any code, so this workbook stays macro-free and .xlsx."
step "Close the editor and go back to Excel."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when both sheets are hidden."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — merged range and defined names"
say "One workbook-scoped name on a merged range, and one sheet-scoped name."
printf '\n'
step "On the Inputs sheet, select B2:C3 → Merge & Center."
step "With the merged cell still selected, click the Name Box (left of the"
step "  formula bar), type  MergedInput  and press Enter."
note "A name created this way is workbook-scoped, which is what we want."
printf '\n'
step "Formulas → Define Name…"
step "  Name:      LocalNote"
step "  Scope:     Notes          ← not Workbook"
step "  Refers to: =Notes!\$A\$5"
step "Click OK."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when both names exist."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — a plain formula and a shared formula"
say "A shared formula is what Excel writes when one formula is filled across"
say "several cells. The tool must never orphan its children, so we need one."
printf '\n'
step "On Inputs, put numbers in A1:A5 —  1  2  3  4  5"
printf '\n'
step "D1:  =SUM(A1:A5)          ← a plain formula"
printf '\n'
step "E1:  =A1*2"
step "Select E1, then DRAG THE FILL HANDLE down to E5."
note "Fill, not copy-paste-into-each-cell: filling is what makes Excel emit"
note "one shared formula with children rather than five plain ones."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when the formulas are in."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — a custom row format and a column style"
say "A row and a column carrying a format while leaving their cells ABSENT."
say "That is what makes an inserted cell inherit a style, and it is the"
say "fiddliest case in the whole tool."
printf '\n'
step "Click the row 7 HEADER to select the whole row → make it Bold."
step "Leave every cell in row 7 EMPTY."
printf '\n'
step "Click the column G HEADER to select the whole column."
step "Format → Cells → Number → Date, so the column carries a date style."
step "Leave every cell in column G EMPTY."
printf '\n'
note "Empty is the point: the format lives on the row and column elements,"
note "with no cell elements underneath."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when the row and column are formatted."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — custom document properties, one of each type"
say "Excel offers exactly four custom property types. We need all four."
printf '\n'
step "File → Properties… → Custom tab"
printf '\n'
step "  Name: Stamp.Text     Type: Text        Value: xlsplice"
step "  Name: Stamp.Number   Type: Number      Value: 42"
step "  Name: Stamp.Flag     Type: Yes or no   Value: Yes"
step "  Name: Stamp.Date     Type: Date        Value: 2026-09-11"
printf '\n'
note "Click Add after each one, then OK. Type matters more than the value:"
note "these become vt:lpwstr, vt:i4/vt:r8, vt:bool and vt:filetime."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when all four properties are added."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — save once, then verify"
say "Everything is built. Save it now, exactly once."
printf '\n'
step "File → Save As → Format: Excel Workbook (.xlsx)"
step "Save it at exactly:  $(pwd)/$FEATURE"
step "Then CLOSE the workbook."
printf '\n'
warn "If Excel warns the workbook cannot be saved without macros, you left"
warn "code in a module. Delete the module and save as .xlsx."
printf '\n'
pause "Press Enter once it is saved and closed."
printf '\n'
if saved "$FEATURE"; then
  wb=$(part "xl/workbook.xml" "$FEATURE")
  sheets=$(part "xl/worksheets/sheet*.xml" "$FEATURE")
  props=$(part "docProps/custom.xml" "$FEATURE")
  names=$(printf '%s' "$wb" | grep -oE '<(x:)?definedName [^>]*>' || true)

  check "a very hidden sheet, veryHidden not merely hidden" "$wb" 'state="veryHidden"'
  check "a hidden sheet" "$wb" 'state="hidden"'
  check "a workbook-scoped defined name" \
    "$(printf '%s' "$names" | grep -v localSheetId || true)" 'definedName'
  check "a sheet-scoped defined name" "$names" 'localSheetId='
  check "a merged range" "$sheets" '<(x:)?mergeCell'
  check "a plain formula" "$sheets" '<(x:)?f>'
  check "a shared formula with children" "$sheets" 't="shared"'
  check "a row with a custom format" "$sheets" 'customFormat="1"'
  check "a column carrying a style" "$sheets" '<(x:)?col [^>]*style="'
  check "custom property of type text" "$props" 'vt:lpwstr'
  check "custom property of type number" "$props" 'vt:(i4|r8|int|decimal)'
  check "custom property of type yes/no" "$props" 'vt:bool'
  check "custom property of type date" "$props" 'vt:filetime'
  refute "no VBA project crept in" "$(unzip -l "$FEATURE")" 'vbaProject\.bin'
fi
verdict "feature.xlsx"
pause

fi  # ── end of the three packages of issue #4 ──────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
stage "4 of 4 · dated-row.xlsx — a row Excel formats as a date"
say "An inserted cell has no style of its own, so it can render as a date"
say "only by taking the one its row carries. No fixture can be asked for that:"
say "row 7 of feature.xlsx declares a custom format, but a bold one. This"
say "package is that row, and it is the whole of what it is for."
printf '\n'
if [[ -f "$DATED" ]]; then
  say "It is already saved, so there is nothing to build here — a fixture's"
  say "bytes are the baseline, and re-saving one is the thing that must not"
  say "happen. The next stage checks the file that is there."
  printf '\n'
  note "$DATED"
  pause
else
  say "Nothing to type: the content is written out and opened for you. A CSV"
  say "is data entry, and what you save from it is still bytes Excel wrote."
  printf '\n'
  CSV_DIR=$(mktemp -d)
  CSV="$CSV_DIR/Inputs.csv"   # a CSV opens under its own file name as the sheet
  {
    printf 'xlsplice fixture for issue #28\n'
    printf 'A row whose custom format is a date format.\n'
    printf '\n\n\n\n'
    printf '2026-09-11\n'
  } >"$CSV"
  note "wrote $CSV"
  if command -v open >/dev/null 2>&1 && open -a "Microsoft Excel" "$CSV" 2>/dev/null; then
    printf '  %s↗ opened%s it in Excel\n' "$GREEN" "$RESET"
  else
    warn "could not open Excel for you, so open that file yourself."
  fi
  printf '\n'
  step "Click the ROW 7 HEADER, to select the whole row rather than a cell."
  step "Format → Cells… → Number → Date → OK."
  printf '\n'
  step "Leave B7 alone: nothing typed into it, nothing deleted out of it."
  printf '\n'
  note "A7 holds the date and the row carries the format. B7 is the cell that"
  note "is not there, which is what a write into it has to insert."
  printf '\n'
  pause "Press Enter when row 7 is formatted as a date."
fi

# ──────────────────────────────────────────────────────────────────────────
stage "dated-row.xlsx — save once, then verify"
if [[ -f "$DATED" ]]; then
  say "Checking the fixture already on disk. Nothing is written to it."
  printf '\n'
else
  say "Save it now, exactly once."
  printf '\n'
  step "File → Save As → Format: Excel Workbook (.xlsx)"
  step "Save it at exactly:  $(pwd)/$DATED"
  step "Then CLOSE the workbook."
  printf '\n'
  warn "Excel will offer to keep the CSV format. It has to be .xlsx, or there"
  warn "is no package here to test at all."
  printf '\n'
  pause "Press Enter once it is saved and closed."
  printf '\n'
fi
if saved "$DATED"; then
  sheet=$(part "xl/worksheets/sheet*.xml" "$DATED")
  dated_row "$DATED" 7
  check "row 7 holds a cell of its own" "$sheet" '<(x:)?c r="A7"'
  refute "B7 is absent, so a write into it is an insertion" "$sheet" '<(x:)?c r="B7"'
  refute "no VBA project crept in" "$(unzip -l "$DATED")" 'vbaProject\.bin'
fi
# A checksum recorded for a fixture that failed its checks is a false green,
# so the note below is told whether this one held.
if (( FAILED == 0 )); then DATED_OK=yes; else DATED_OK=no; fi
verdict "dated-row.xlsx"
# An `if`, not a `&&` list: under `set -e` a false test as a whole statement
# is an exit, and on the run that only verifies there is no CSV to remove.
if [[ -n "${CSV_DIR:-}" ]]; then
  rm -rf "$CSV_DIR"
fi
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Record the note and stage for commit"
say "Issue #4 asks for a short note naming what each file contains, and #28"
say "adds the fourth to it. The note is written from the files themselves."
printf '\n'

# The date the fourth was saved is a fact about the file, not about this run,
# so a re-run reads back the one already recorded rather than stamping today.
FOURTH_SAVED=$(date +%Y-%m-%d)
if recorded=$(grep -oE 'dated-row\.xlsx` on [0-9]{4}-[0-9]{2}-[0-9]{2}' \
  "$FIXTURES/README.md" 2>/dev/null | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}'); then
  FOURTH_SAVED=$recorded
fi

# Whether the fixtures still carry Excel's author and path stamps, or had
# them taken out once (the note explains). Read from the files, like the
# rest of the note; the date of that edit is read back the same way.
EDITED=yes
for f in "$PLAIN" "$MACROS" "$FEATURE" "$DATED"; do
  if unzip -p "$f" xl/workbook.xml 2>/dev/null | grep -q 'absPath'; then EDITED=no; fi
done
EDITED_ON=$(date +%Y-%m-%d)
if recorded=$(grep -oE 'On [0-9]{4}-[0-9]{2}-[0-9]{2} those two parts' \
  "$FIXTURES/README.md" 2>/dev/null | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}'); then
  EDITED_ON=$recorded
fi

if [[ ! -f "$PLAIN" || ! -f "$MACROS" || ! -f "$FEATURE" || ! -f "$DATED" ]]; then
  warn "a fixture is missing, so the note is left exactly as it is."
  note "Nothing is recorded until all four are saved."
elif [[ "${DATED_OK:-no}" != yes ]]; then
  warn "dated-row.xlsx did not meet its checks, so the note is left alone."
  note "Save it again from Excel — it has no byte history to protect until it"
  note "is committed — and run this wizard once more."
else
{
  printf '# Fixtures\n\n'
  printf 'Four packages saved from Excel by hand: three for issue #4 and a fourth\n'
  printf 'for issue #28. A fixture is a package **Excel saved**: never re-save one,\n'
  printf 'never regenerate one with a library, and never put vendor material in\n'
  printf 'one. Their bytes are the baseline every byte-preservation test compares\n'
  printf 'against.\n\n'
  printf -- '- `plain.xlsx` — one visible sheet: a few numbers, a text, a date\n'
  printf '  formatted as a date, and a boolean.\n'
  printf -- '- `macros.xlsm` — a real VBA project (`xl/vbaProject.bin`) holding one\n'
  printf '  trivial macro, so the pass-through of the VBA part is exercised.\n'
  printf -- '- `feature.xlsx` — a merged range with a workbook-scoped defined name on\n'
  printf '  it; a sheet-scoped defined name; a plain formula and a shared formula\n'
  printf '  filled across several cells; a hidden sheet and a very hidden sheet; a\n'
  printf '  row with a custom row format and a column with a column style, both\n'
  printf '  leaving their cells absent; and custom document properties of each of\n'
  printf '  the four types Excel offers.\n'
  printf -- '- `dated-row.xlsx` — one sheet, `Inputs`, whose row 7 carries a custom\n'
  printf '  row format that is a **date** format, with `B7` left absent. A date\n'
  printf '  written into `B7` renders as a date only by inheriting the style of\n'
  printf '  its row, which is the half of inheritance no other fixture holds.\n\n'
  printf 'Saved with Excel %s — the first three on %s, and\n' \
    "${EXCEL_VERSION:-16.x}" "$FIRST_SAVED"
  printf '`dated-row.xlsx` on %s.\n\n' "$FOURTH_SAVED"
  if [[ $EDITED == yes ]]; then
    printf '## The one edit\n'
    printf '\n'
    printf 'Excel stamps the saving user into `docProps/core.xml` (`dc:creator`,\n'
    printf '`cp:lastModifiedBy`) and the absolute path it saved to into\n'
    printf '`xl/workbook.xml` (`x15ac:absPath`), and both ship with every release.\n'
    printf 'On %s those two parts were edited once in each fixture to take\n' "$EDITED_ON"
    printf 'them out. Nothing else was touched: every other entry is Excel'\''s, copied\n'
    printf 'raw -- header, compressed bytes and central-directory record -- with only\n'
    printf 'its offset moved, so the flags, the creator system and the zeroed\n'
    printf 'timestamp that the writer'\''s raw copy is tested against are still the ones\n'
    printf 'Excel wrote. The two edited parts were compressed afresh under the\n'
    printf 'original entry'\''s own flags, version and timestamp. That edit is not a\n'
    printf 're-save and does not move the baseline; a future fixture avoids the need\n'
    printf 'for it by clearing the author fields before saving, as `save-fixtures.sh`\n'
    printf 'says.\n\n'
  else
    printf 'Excel stamps the absolute path it saved to into `xl/workbook.xml`, as\n'
    printf '`x15ac:absPath`. Taking it out would mean editing the file, which is the one\n'
    printf 'thing a fixture must not have had done to it, so it stays.\n\n'
  fi
  printf '## Checksums\n\n'
  printf 'If one of these ever changes, a fixture was re-saved and the baseline\n'
  printf 'moved. That is a bug, not an update.\n\n'
  printf '```\n'
  shasum -a 256 "$PLAIN" "$MACROS" "$FEATURE" "$DATED" 2>/dev/null | sed "s| .*/| |"
  printf '```\n\n'
  printf '## The oracle\n\n'
  printf '`tests/oracle.rs` puts these in front of a real Excel and asks whether it\n'
  printf 'opens them without complaint. Those cases are ignored by default, and the\n'
  printf 'way to run them is:\n\n'
  printf '```\n'
  printf 'scripts/oracle.sh\n'
  printf '```\n\n'
  printf 'One at a time, because there is one Excel and they take turns at it. Run\n'
  printf 'them that way rather than by hand: the script exports what the suite reads,\n'
  printf 'so a suite of skips cannot pass itself off as a suite of verdicts. See\n'
  printf '`docs/adr/0006-the-oracle-hands-excel-the-file-and-reads-the-screen.md` for\n'
  printf 'what that costs and why.\n'
} >"$FIXTURES/README.md"
note "wrote $FIXTURES/README.md"
printf '\n'
shasum -a 256 "$PLAIN" "$MACROS" "$FEATURE" "$DATED" 2>/dev/null || true
printf '\n'
fi
if confirm "Stage the fixtures and the note for commit?"; then
  git add "$FIXTURES"
  note "staged. Review with 'git diff --cached --stat', then commit."
else
  note "left unstaged; 'git add $FIXTURES' when you are ready."
fi

finish
note "Next: tell the agent the fixture has landed. It will point the oracle"
note "case a_date_inheriting_a_date_style_from_its_row_opens_clean at it,"
note "delete the derivation that stood in for it, and close #28."
printf '\n'
note "Then put it in front of Excel: scripts/oracle.sh"
printf '\n'
