#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=10

FIXTURES="tests/fixtures"
PLAIN="$FIXTURES/plain.xlsx"
MACROS="$FIXTURES/macros.xlsm"
FEATURE="$FIXTURES/feature.xlsx"

# ── Verification helpers ──────────────────────────────────────────────────
# Issue #4 can be got subtly wrong in ways that only bite three tickets
# later, so every file is unzipped and checked the moment it is saved.

FAILED=0

# part PATTERN FILE: the text of the matching part(s) of a package.
part() { unzip -p "$2" "$1" 2>/dev/null || true; }

# check "label" HAYSTACK REGEX: pass when the regex matches.
check() {
  if printf '%s' "$2" | grep -qE "$3"; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  else
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"
    FAILED=$((FAILED + 1))
  fi
}

# refute "label" HAYSTACK REGEX: pass when the regex does NOT match.
refute() {
  if printf '%s' "$2" | grep -qE "$3"; then
    printf '  %s✗%s %s\n' "$RED" "$RESET" "$1"
    FAILED=$((FAILED + 1))
  else
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"
  fi
}

# saved FILE: the file exists and is a zip container.
saved() {
  if [[ ! -f "$1" ]]; then
    printf '  %s✗%s %s was not saved to that path\n' "$RED" "$RESET" "$1"
    FAILED=$((FAILED + 1)); return 1
  fi
  if ! unzip -l "$1" >/dev/null 2>&1; then
    printf '  %s✗%s %s is not a package\n' "$RED" "$RESET" "$1"
    FAILED=$((FAILED + 1)); return 1
  fi
  printf '  %s✓%s %s saved (%s)\n' "$GREEN" "$RESET" "$1" "$(du -h "$1" | cut -f1)"
}

# verdict "name": report and let the human retry the stage.
verdict() {
  if (( FAILED == 0 )); then
    printf '\n  %s%s✓ %s meets the ticket%s\n' "$BOLD" "$GREEN" "$1" "$RESET"
  else
    printf '\n'
    warn "$FAILED check(s) failed on $1."
    note "Fix it in Excel and save over the same path, then re-run this wizard."
    note "A file that never left Excel has no byte history to protect yet, so"
    note "re-saving now is free. Once it is committed, it must not be re-saved."
  fi
  FAILED=0
}

banner "xlsplice fixtures (issue #4)"

# ──────────────────────────────────────────────────────────────────────────
stage "Ground rules"
say "Three packages go into $FIXTURES/, saved by you from Excel."
printf '\n'
step "Keep every file small: a handful of cells, no styling beyond what is asked."
step "No vendor material. Nothing from a the vendor system Template, not one cell."
step "Save each file ONCE and never re-save it. Its bytes are the test baseline."
step "Build each workbook completely BEFORE saving, so one save is enough."
printf '\n'
if ! command -v unzip >/dev/null 2>&1; then
  warn "unzip is not on PATH, so this wizard cannot verify what you save."
  exit 1
fi
mkdir -p "$FIXTURES"
note "created $FIXTURES/"
pause "Ready?"

# ──────────────────────────────────────────────────────────────────────────
stage "1 of 3 · plain.xlsx"
say "A plain workbook: one visible sheet, a few numbers, a text, a date"
say "formatted as a date, and a boolean."
printf '\n'
step "Excel → File → New Blank Workbook. Leave the one sheet as Sheet1."
step "A1: 1     A2: 2.5     A3: -3"
step "B1: hello"
step "C1: 2026-09-11 — then Format → Cells → Date, so it is a DATE not text."
step "D1: TRUE   (type the word; Excel stores a real boolean)"
printf '\n'
step "File → Save As → Format: Excel Workbook (.xlsx)"
step "Save it at exactly:  $(pwd)/$PLAIN"
step "Then CLOSE the workbook."
printf '\n'
pause "Press Enter once it is saved and closed."
printf '\n'
if saved "$PLAIN"; then
  wb=$(part "xl/workbook.xml" "$PLAIN")
  sheet=$(part "xl/worksheets/sheet*.xml" "$PLAIN")
  styles=$(part "xl/styles.xml" "$PLAIN")
  # BSD grep -c counts matches, GNU grep -c counts lines, and Excel writes
  # workbook.xml as one long line. Count with wc so both agree.
  check "exactly one sheet" \
    "$(printf '%s' "$wb" | grep -oE '<(x:)?sheet ' | wc -l | tr -d ' ')" '^1$'
  refute "that sheet is visible" "$wb" 'state="(hidden|veryHidden)"'
  check "holds a boolean cell" "$sheet" 't="b"'
  check "holds a text cell" "$sheet" 't="(s|inlineStr|str)"'
  check "holds numeric values" "$sheet" '<(x:)?v>'
  check "a date number format is defined" "$styles" 'numFmtId="(1[4-9]|2[0-2]|4[5-7])"|formatCode="[^"]*(yy|dd|mmm)'
fi
verdict "plain.xlsx"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "2 of 3 · macros.xlsm"
say "A macro-enabled workbook with a REAL VBA project, so the pass-through of"
say "xl/vbaProject.bin is exercised. Any trivial macro will do."
printf '\n'
step "Excel → File → New Blank Workbook."
step "A1: 1"
step "Tools → Macro → Visual Basic Editor   (or Developer → Visual Basic)"
step "In the editor: Insert → Module, then paste exactly:"
printf '\n      %sSub Hello()%s\n' "$DIM" "$RESET"
printf '      %s    MsgBox "hi"%s\n' "$DIM" "$RESET"
printf '      %sEnd Sub%s\n\n' "$DIM" "$RESET"
step "Close the editor and go back to Excel."
printf '\n'
step "File → Save As → Format: Excel Macro-Enabled Workbook (.xlsm)"
step "Save it at exactly:  $(pwd)/$MACROS"
step "Then CLOSE the workbook."
printf '\n'
warn "A .xlsm with no module saves no vbaProject.bin. The macro is the point."
printf '\n'
pause "Press Enter once it is saved and closed."
printf '\n'
if saved "$MACROS"; then
  listing=$(unzip -l "$MACROS" 2>/dev/null || true)
  types=$(part "\[Content_Types\].xml" "$MACROS")
  check "carries a real VBA project (xl/vbaProject.bin)" "$listing" 'xl/vbaProject\.bin'
  check "the VBA part is not empty" \
    "$(printf '%s' "$listing" | grep -E 'vbaProject\.bin' | awk '{print $1}')" '^[1-9][0-9]*$'
  check "declared macro-enabled in [Content_Types].xml" "$types" 'sheet\.macroEnabled\.main\+xml'
fi
verdict "macros.xlsm"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "3 of 3 · feature.xlsx — sheets and visibility"
say "The feature workbook is built across the next five stages and saved ONCE"
say "at the end. Do not save until this wizard tells you to."
printf '\n'
step "Excel → File → New Blank Workbook."
step "Rename Sheet1 to:  Inputs"
step "Add two more sheets, named:  Notes  and  Parameters"
step "On Notes, put any text in A5 (a sheet-scoped name will point there)."
printf '\n'
say "Now hide two of them. Do the plain hide first:"
step "Right-click the Notes tab → Hide"
printf '\n'
say "veryHidden cannot be set from the worksheet UI. Use the VBA editor:"
step "Click the Inputs tab first, so the feature workbook is the active one."
step "Tools → Macro → Visual Basic Editor"
step "View → Immediate Window, then type this line and press Enter:"
printf '\n      %sActiveWorkbook.Sheets("Parameters").Visible = 2%s\n\n' "$DIM" "$RESET"
note "2 is xlSheetVeryHidden. The Immediate window runs the line without"
note "storing any code, so this workbook stays macro-free and .xlsx."
step "Close the editor and go back to Excel."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when both sheets are hidden."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — merged range and defined names"
say "One workbook-scoped name on a merged range, and one sheet-scoped name."
printf '\n'
step "On the Inputs sheet, select B2:C3 → Merge & Center."
step "With the merged cell still selected, click the Name Box (left of the"
step "  formula bar), type  MergedInput  and press Enter."
note "A name created this way is workbook-scoped, which is what we want."
printf '\n'
step "Formulas → Define Name…"
step "  Name:      LocalNote"
step "  Scope:     Notes          ← not Workbook"
step "  Refers to: =Notes!\$A\$5"
step "Click OK."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when both names exist."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — a plain formula and a shared formula"
say "A shared formula is what Excel writes when one formula is filled across"
say "several cells. The tool must never orphan its children, so we need one."
printf '\n'
step "On Inputs, put numbers in A1:A5 —  1  2  3  4  5"
printf '\n'
step "D1:  =SUM(A1:A5)          ← a plain formula"
printf '\n'
step "E1:  =A1*2"
step "Select E1, then DRAG THE FILL HANDLE down to E5."
note "Fill, not copy-paste-into-each-cell: filling is what makes Excel emit"
note "one shared formula with children rather than five plain ones."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when the formulas are in."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — a custom row format and a column style"
say "A row and a column carrying a format while leaving their cells ABSENT."
say "That is what makes an inserted cell inherit a style, and it is the"
say "fiddliest case in the whole tool."
printf '\n'
step "Click the row 7 HEADER to select the whole row → make it Bold."
step "Leave every cell in row 7 EMPTY."
printf '\n'
step "Click the column G HEADER to select the whole column."
step "Format → Cells → Number → Date, so the column carries a date style."
step "Leave every cell in column G EMPTY."
printf '\n'
note "Empty is the point: the format lives on the row and column elements,"
note "with no cell elements underneath."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when the row and column are formatted."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — custom document properties, one of each type"
say "Excel offers exactly four custom property types. We need all four."
printf '\n'
step "File → Properties… → Custom tab"
printf '\n'
step "  Name: Stamp.Text     Type: Text        Value: xlsplice"
step "  Name: Stamp.Number   Type: Number      Value: 42"
step "  Name: Stamp.Flag     Type: Yes or no   Value: Yes"
step "  Name: Stamp.Date     Type: Date        Value: 2026-09-11"
printf '\n'
note "Click Add after each one, then OK. Type matters more than the value:"
note "these become vt:lpwstr, vt:i4/vt:r8, vt:bool and vt:filetime."
printf '\n'
warn "Still do NOT save."
pause "Press Enter when all four properties are added."

# ──────────────────────────────────────────────────────────────────────────
stage "feature.xlsx — save once, then verify"
say "Everything is built. Save it now, exactly once."
printf '\n'
step "File → Save As → Format: Excel Workbook (.xlsx)"
step "Save it at exactly:  $(pwd)/$FEATURE"
step "Then CLOSE the workbook."
printf '\n'
warn "If Excel warns the workbook cannot be saved without macros, you left"
warn "code in a module. Delete the module and save as .xlsx."
printf '\n'
pause "Press Enter once it is saved and closed."
printf '\n'
if saved "$FEATURE"; then
  wb=$(part "xl/workbook.xml" "$FEATURE")
  sheets=$(part "xl/worksheets/sheet*.xml" "$FEATURE")
  props=$(part "docProps/custom.xml" "$FEATURE")
  names=$(printf '%s' "$wb" | grep -oE '<(x:)?definedName [^>]*>' || true)

  check "a very hidden sheet, veryHidden not merely hidden" "$wb" 'state="veryHidden"'
  check "a hidden sheet" "$wb" 'state="hidden"'
  check "a workbook-scoped defined name" \
    "$(printf '%s' "$names" | grep -v localSheetId || true)" 'definedName'
  check "a sheet-scoped defined name" "$names" 'localSheetId='
  check "a merged range" "$sheets" '<(x:)?mergeCell'
  check "a plain formula" "$sheets" '<(x:)?f>'
  check "a shared formula with children" "$sheets" 't="shared"'
  check "a row with a custom format" "$sheets" 'customFormat="1"'
  check "a column carrying a style" "$sheets" '<(x:)?col [^>]*style="'
  check "custom property of type text" "$props" 'vt:lpwstr'
  check "custom property of type number" "$props" 'vt:(i4|r8|int|decimal)'
  check "custom property of type yes/no" "$props" 'vt:bool'
  check "custom property of type date" "$props" 'vt:filetime'
  refute "no VBA project crept in" "$(unzip -l "$FEATURE")" 'vbaProject\.bin'
fi
verdict "feature.xlsx"
pause

# ──────────────────────────────────────────────────────────────────────────
stage "Record the note and stage for commit"
say "Issue #4 asks for a short note naming what each file contains."
printf '\n'
{
  printf '# Fixtures\n\n'
  printf 'Three packages saved from Excel by hand for issue #4. A fixture is a\n'
  printf 'package **Excel saved**: never re-save one, never regenerate one with a\n'
  printf 'library, and never put vendor material in one. Their bytes are the\n'
  printf 'baseline every byte-preservation test compares against.\n\n'
  printf -- '- `plain.xlsx` — one visible sheet: a few numbers, a text, a date\n'
  printf '  formatted as a date, and a boolean.\n'
  printf -- '- `macros.xlsm` — a real VBA project (`xl/vbaProject.bin`) holding one\n'
  printf '  trivial macro, so the pass-through of the VBA part is exercised.\n'
  printf -- '- `feature.xlsx` — a merged range with a workbook-scoped defined name on\n'
  printf '  it; a sheet-scoped defined name; a plain formula and a shared formula\n'
  printf '  filled across several cells; a hidden sheet and a very hidden sheet; a\n'
  printf '  row with a custom row format and a column with a column style, both\n'
  printf '  leaving their cells absent; and custom document properties of each of\n'
  printf '  the four types Excel offers.\n\n'
  printf 'Saved with Excel %s on %s.\n\n' "${EXCEL_VERSION:-16.x}" "$(date +%Y-%m-%d)"
  printf '## Checksums\n\n'
  printf 'If one of these ever changes, a fixture was re-saved and the baseline\n'
  printf 'moved. That is a bug, not an update.\n\n'
  printf '```\n'
  shasum -a 256 "$PLAIN" "$MACROS" "$FEATURE" 2>/dev/null | sed "s| .*/| |"
  printf '```\n'
} > "$FIXTURES/README.md"
note "wrote $FIXTURES/README.md"
printf '\n'
shasum -a 256 "$PLAIN" "$MACROS" "$FEATURE" 2>/dev/null || true
printf '\n'
if confirm "Stage all three fixtures and the note for commit?"; then
  git add "$FIXTURES"
  note "staged. Review with 'git diff --cached --stat', then commit."
else
  note "left unstaged; 'git add $FIXTURES' when you are ready."
fi

finish
note "Next: tell the agent the fixtures have landed. It will re-point the"
note "tests in tests/support/mod.rs at the real bytes and close #4."
printf '\n'
